using Collector.Application.Knowledge;
using Collector.Application.Ports;
using Collector.Domain.Enums;
using Collector.Domain.Knowledge;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Collector.Infrastructure.Export;

public sealed class QuestPdfKnowledgeExporter : IKnowledgePdfExporter
{
    private const string DateFormat = "yyyy-MM-dd HH:mm";

    static QuestPdfKnowledgeExporter()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task ExportAsync(KnowledgePdfReport report, string outputPath, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        Document.Create(container => Compose(container, report)).GeneratePdf(outputPath);
        return Task.CompletedTask;
    }

    private static void Compose(IDocumentContainer container, KnowledgePdfReport report)
    {
        container.Page(page =>
        {
            page.Margin(36);
            page.Size(PageSizes.A4);
            page.Header().Element(header => ComposeHeader(header, report));
            page.Content().PaddingTop(12).Column(column =>
            {
                column.Spacing(14);
                foreach (var group in report.Items.GroupBy(item => item.DocumentName).OrderBy(g => g.Key, StringComparer.Ordinal))
                {
                    column.Item().Element(section => ComposeDocument(section, group.Key, group));
                }
            });
            page.Footer().AlignCenter().Text(text =>
            {
                text.CurrentPageNumber();
                text.Span(" / ");
                text.TotalPages();
            });
        });
    }

    private static void ComposeHeader(IContainer container, KnowledgePdfReport report)
    {
        container.Column(column =>
        {
            column.Item().Text("Cortexa Knowledge Export").FontSize(18).Bold();
            column.Item().PaddingTop(4).Text(
                $"Generated by {report.GeneratedBy} on {report.GeneratedAt.ToLocalTime().ToString(DateFormat)} · " +
                $"{report.Provider} · {report.Model} · {report.Items.Count} items");
            column.Item().PaddingTop(8).LineHorizontal(1);
        });
    }

    private static void ComposeDocument(IContainer container, string documentName, IEnumerable<ExtractedKnowledgeItem> items)
    {
        container.Column(column =>
        {
            column.Spacing(8);
            column.Item().Text(documentName).FontSize(13).Bold();
            foreach (var item in items)
            {
                column.Item().Element(itemContainer => ComposeItem(itemContainer, item));
            }
        });
    }

    private static void ComposeItem(IContainer container, ExtractedKnowledgeItem item)
    {
        container.Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(column =>
        {
            column.Spacing(4);
            column.Item().Row(row =>
            {
                row.AutoItem().Background(Colors.Blue.Lighten4).Padding(4).Text(KindLabel(item.Kind)).FontSize(9).Bold();
                row.RelativeItem();
                row.AutoItem().Text(FormatSource(item.Source)).FontSize(9).FontColor(Colors.Grey.Darken1);
            });
            column.Item().Text(item.Title).FontSize(12).Bold();
            column.Item().Text(item.Summary).FontSize(10);
            if (!string.IsNullOrWhiteSpace(item.Details))
            {
                column.Item().Text(item.Details).FontSize(10).FontColor(Colors.Grey.Darken2);
            }

            if (!string.IsNullOrWhiteSpace(item.Excerpt))
            {
                column.Item().Background(Colors.Grey.Lighten4).Padding(6).Text($"“{item.Excerpt}”").FontSize(9).Italic();
            }
        });
    }

    private static string KindLabel(KnowledgeKind kind) => kind switch
    {
        KnowledgeKind.Logic => "Logic",
        KnowledgeKind.Algorithm => "Algorithm",
        KnowledgeKind.Method => "Method",
        KnowledgeKind.Layer => "Layer",
        KnowledgeKind.DataModel => "Data model",
        KnowledgeKind.Interface => "Interface",
        KnowledgeKind.Workflow => "Workflow",
        KnowledgeKind.KeyContent => "Key content",
        _ => kind.ToString(),
    };

    private static string FormatSource(KnowledgeSource source)
    {
        if (!string.IsNullOrWhiteSpace(source.FilePath))
        {
            return source.LineStart is { } first
                ? $"{source.FilePath} · line {first}{(source.LineEnd is { } last && last != first ? $"-{last}" : string.Empty)}"
                : source.FilePath;
        }

        var parts = new List<string>(2);
        if (source.PageNumber is { } page)
        {
            parts.Add($"Page {page}");
        }

        if (!string.IsNullOrWhiteSpace(source.Section))
        {
            parts.Add(source.Section);
        }

        return parts.Count > 0 ? string.Join(" · ", parts) : string.Empty;
    }
}
