import { Text, View } from '@react-pdf/renderer';
import { pdfBaseStyles } from './pdfStyles';

export function PdfPageFooter() {
  return (
    <View style={pdfBaseStyles.footer} fixed>
      <View style={pdfBaseStyles.footerHairline} />
      <View style={pdfBaseStyles.footerRow}>
        <Text style={pdfBaseStyles.footerText}>Generated by Cortexa</Text>
        <Text
          style={pdfBaseStyles.footerText}
          render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
        />
      </View>
    </View>
  );
}
